# Generated by Django 4.1 on 2022-08-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cine',
            fields=[
                ('id_cine', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pelicula_cine', models.CharField(max_length=50)),
                ('nombre_director_cine', models.CharField(max_length=50)),
                ('anio_lanzamiento_cine', models.IntegerField()),
                ('email_usuario_cine', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Literatura',
            fields=[
                ('id_literatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_literatura', models.CharField(max_length=50)),
                ('autor_literatura', models.CharField(max_length=50)),
                ('editorial_literatura', models.CharField(max_length=50)),
                ('anio_edicion_literatura', models.IntegerField()),
                ('email_usuario_literatura', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id_musica', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_artista_musica', models.CharField(max_length=50)),
                ('nombre_disco_musica', models.CharField(max_length=50)),
                ('anio_lanzamiento_musica', models.IntegerField()),
                ('email_usuario_musica', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('apellido_usuario', models.CharField(max_length=50)),
                ('fecha_nacimiento_usuario', models.DateField()),
                ('email_usuario', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
