# Generated by Django 4.1 on 2022-08-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pelicula_cine', models.CharField(max_length=50)),
                ('nombre_director_cine', models.CharField(max_length=50)),
                ('anio_lanzamiento_cine', models.CharField(max_length=50)),
                ('email_usuario_cine', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Literatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_literatura', models.CharField(max_length=50)),
                ('autor_literatura', models.CharField(max_length=50)),
                ('editorial_literatura', models.CharField(max_length=50)),
                ('anio_edicion_literatura', models.IntegerField()),
                ('email_usuario_literatura', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_artista_musica', models.CharField(max_length=50)),
                ('nombre_disco_musica', models.CharField(max_length=50)),
                ('anio_lanzamiento_musica', models.CharField(max_length=50)),
                ('email_usuario_musica', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('apellido_usuario', models.CharField(max_length=50)),
                ('fecha_nacimiento_usuario', models.DateField(max_length=8)),
                ('email_usuario', models.EmailField(max_length=254)),
            ],
        ),
    ]
