# Generated by Django 4.1 on 2022-09-08 23:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppTPFinal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='literatura',
            name='fecha_creacion_literatura',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
