# Generated by Django 4.1 on 2022-08-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTPFinal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cine',
            name='anio_lanzamiento_cine',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='musica',
            name='anio_lanzamiento_musica',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento_usuario',
            field=models.DateField(),
        ),
    ]
