# Generated by Django 4.1 on 2022-09-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTPFinal', '0003_cine_fecha_creacion_musica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='literatura',
            name='email_usuario_literatura',
        ),
        migrations.AddField(
            model_name='literatura',
            name='username_literatura',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
