# Generated by Django 4.1 on 2022-09-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTPFinal', '0004_remove_literatura_email_usuario_literatura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cine',
            name='email_usuario_cine',
        ),
        migrations.RemoveField(
            model_name='musica',
            name='email_usuario_musica',
        ),
        migrations.AddField(
            model_name='cine',
            name='username_cine',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musica',
            name='username_musica',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
